#pragma once
#define INJECTOR_OK 0
#define INJECTOR_NO_PARAMS 1
#define INJECTOR_INVALID_PARAMS 2
#define INJECTOR_PROCESS_NOT_FOUND 3
#define INJECTOR_DLL_NOT_FOUND 4
#define INJECTOR_FAILED_TO_GET_PROCESSES 5